# Generated by Django 3.2.5 on 2021-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('qual', models.CharField(max_length=20, verbose_name='Квалификация')),
                ('date', models.DateField(verbose_name='Дата поступления')),
                ('prov', models.CharField(max_length=20, verbose_name='Поставщик')),
                ('srok', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('place', models.CharField(max_length=30, verbose_name='Место хранения')),
                ('mass', models.FloatField(blank=True, null=True, verbose_name='Масса, кг')),
            ],
        ),
    ]
