# Generated by Django 3.2.5 on 2021-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='prov',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='react',
            name='qual',
            field=models.CharField(choices=[('Ч', 'ч'), ('ЧДА', 'чда'), ('ХЧ', 'хч'), ('ОСЧ', 'осч'), ('----------', '----------')], default='----------', max_length=10, verbose_name='Квалификация'),
        ),
    ]
