# Generated by Django 3.2.5 on 2021-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsklad', '0002_auto_20210729_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='clas',
            field=models.CharField(default='не опасен', max_length=15, verbose_name='Класс опасности'),
        ),
        migrations.AlterField(
            model_name='react',
            name='date',
            field=models.DateField(verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='react',
            name='qual',
            field=models.CharField(choices=[('имп', 'ИМП'), ('ч', 'Ч'), ('чда', 'ЧДА'), ('хч', 'ХЧ'), ('осч', 'ОСЧ'), ('----------', '----------')], default='----------', max_length=10, verbose_name='Квалификация'),
        ),
    ]
